{
  "description": "每5分钟检测一次，过去5分钟内，定时SQL任务出现报错后，触发告警。",
  "alert": {
    "name": "sls_app_sche_sql_at_err_monitor",
    "displayName": "定时SQL任务执行错误监控",
    "type": "Alert",
    "state": "Enabled",
    "schedule": {
      "type": "FixedRate",
      "interval": "5m"
    },
    "configuration": {
      "version": "2.0",
      "type": "default",
      "dashboard": "internal-alert-analysis",
      "queryList": [
        {
          "storeType": "log",
          "project": "{{default.project}}",
          "store": "internal-diagnostic_log",
          "query": "__topic__: scheduled_sql_alert not Status: SUCCEEDED | select project, job_name, count(1) as cnt from log where regexp_like(project, '.*') and regexp_like(job_name, '.*') group by project, job_name limit 10000",
          "timeSpanType": "Truncated",
          "start": "-5m",
          "end": "now"
        }
      ],
      "groupConfiguration": {
        "type": "custom",
        "fields": [
          "project",
          "job_name"
        ]
      },
      "joinConfigurations": [],
      "severityConfigurations": [
        {
          "severity": 8,
          "evalCondition": {
            "condition": "",
            "countCondition": ""
          }
        }
      ],
      "labels": [],
      "annotations": [
        {
          "key": "desc",
          "value": "过去5分钟内，Project “${project}”下的定时SQL任务“${job_name}”出现了${cnt}次报错。请检查是否存在异常。"
        },
        {
          "key": "title",
          "value": "定时SQL任务执行失败"
        }
      ],
      "autoAnnotation": true,
      "sendResolved": false,
      "threshold": 1,
      "noDataFire": false,
      "noDataSeverity": 6
    }
  }
}